USE COMERCIO_OLTP
GO

INSERT INTO FORMA_PAGAMENTO VALUES('Tranferência', 'Vista')
INSERT INTO FORMA_PAGAMENTO VALUES('Depósito', 'Vista')
INSERT INTO FORMA_PAGAMENTO VALUES('Boleto', 'Vista')
INSERT INTO FORMA_PAGAMENTO VALUES('Cartão Master', 'Vencimento')
INSERT INTO FORMA_PAGAMENTO VALUES('Cartão Master', '2')
INSERT INTO FORMA_PAGAMENTO VALUES('Cartão Master', '3')
INSERT INTO FORMA_PAGAMENTO VALUES('Cartão Master', '4')
INSERT INTO FORMA_PAGAMENTO VALUES('Cartão Master', '5')
INSERT INTO FORMA_PAGAMENTO VALUES('Cartão Master', '10')
INSERT INTO FORMA_PAGAMENTO VALUES('Cartão Visa', 'Vencimento')
INSERT INTO FORMA_PAGAMENTO VALUES('Cartão Visa', '2')
INSERT INTO FORMA_PAGAMENTO VALUES('Cartão Visa', '3')
INSERT INTO FORMA_PAGAMENTO VALUES('Cartão Visa', '4')
INSERT INTO FORMA_PAGAMENTO VALUES('Cartão Visa', '5')
INSERT INTO FORMA_PAGAMENTO VALUES('Cartão Visa', '10')
INSERT INTO FORMA_PAGAMENTO VALUES('Cartão American', 'Vencimento')
INSERT INTO FORMA_PAGAMENTO VALUES('Cartão American', '5')
INSERT INTO FORMA_PAGAMENTO VALUES('Cartão American', '10')
INSERT INTO FORMA_PAGAMENTO VALUES('Cartão American', '12')
INSERT INTO FORMA_PAGAMENTO VALUES('Pay Pall', 'Vista')
INSERT INTO FORMA_PAGAMENTO VALUES('Cartão Visa', '2')
INSERT INTO FORMA_PAGAMENTO VALUES('Cartão Visa', '3')
INSERT INTO FORMA_PAGAMENTO VALUES('Cartão Visa', '4')
INSERT INTO FORMA_PAGAMENTO VALUES('Pay Pall', '5')
INSERT INTO FORMA_PAGAMENTO VALUES('Pay Pall', '12')
INSERT INTO FORMA_PAGAMENTO VALUES('Pag Seguro Web', 'Vista')
GO



