CREATE DATABASE COMERCIO_STAGE
GO

USE COMERCIO_STAGE
GO

--TODO "POR" É UM CANDIDATO A SER UMA DIMENSÃO
--CLIENTE
--VENDEDOR
--CATEGORIA
--FORNECEDOR
--PRODUTO
--FORMA PAGAMENTO
-- O QUE FALAMOS ANTES DO "POR" É UM "FATO", O QUE OCORREU
--FATO SÃO AS MEDIDAS
		-- EX: TOTAL, QUANTIDADE, CUSTO, LUCRO