/*Atualiza Notas Fiscais*/

CREATE VIEW V_NOTA_FISCAL AS 
SELECT ID_NOTA_FISCAL, SUM(TOTAL) AS SOMA
FROM ITEM_NOTA
GROUP BY ID_NOTA_FISCAL
--ORDER BY 1 quando cria-se uma view não se usa Order by

SELECT * FROM V_NOTA_FISCAL
ORDER BY 1

CREATE VIEW V_CARGA_NF AS
SELECT N.IDNOTA, N.TOTAL AS TOTAL_NOTA, V.SOMA 
FROM NOTA_FISCAL N
INNER JOIN V_NOTA_FISCAL V
ON IDNOTA = ID_NOTA_FISCAL

SELECT * FROM V_CARGA_NF

UPDATE V_CARGA_NF
SET TOTAL_NOTA = SOMA
GO

SELECT * FROM NOTA_FISCAL
--nota 1000, total 18600.00
SELECT * FROM ITEM_NOTA
where ID_NOTA_FISCAL = '1000'
--ORDER BY 3

/*CRIANDO EM RELATÓRIO*/

CREATE VIEW V_RELATORIO_OLTP AS
SELECT C.NOME, C.SOBRENOME, C.SEXO, NF.DATA, NF.IDNOTA, P.PRODUTO, I.TOTAL AS VALOR_PRODUTO, NF.TOTAL
FROM CLIENTE C
INNER JOIN NOTA_FISCAL NF
ON C.IDCLIENTE = NF.ID_CLIENTE
INNER JOIN ITEM_NOTA I
ON NF.IDNOTA = I.ID_NOTA_FISCAL
INNER JOIN PRODUTO P
ON P.IDPRODUTO = I.ID_PRODUTO
--ORDER BY NF.IDNOTA
GO

SELECT * FROM V_RELATORIO_OLTP R
ORDER BY R.IDNOTA