SELECT ESTADO, ANO,
SUM(LUCROTOTAL) AS LUCRO,
SUM(QUANTIDADE) AS QTD,
SUM(TOTALITEM) AS TOTAL,
SUM(CUSTOTOTAL) AS CUSTO
FROM DIM_CLIENTE
INNER JOIN FATO F
ON IDSK = F.IDCLIENTE
INNER JOIN DIM_TEMPO T
ON T.IDSK = IDTEMPO
GROUP BY ESTADO, ANO
ORDER BY 1,2
