SELECT * FROM COMERCIO_STAGE.DBO.ST_CATEGORIA
WHERE IDCATEGORIA NOT IN
(SELECT IDCATEGORIA FROM COMERCIO_DW.DBO.CATEGORIA)

SELECT * FROM COMERCIO_DW.DBO.CATEGORIA

SELECT * FROM COMERCIO_STAGE.DBO.ST_CATEGORIA


