CREATE DATABASE COMERCIO_DW
--DROP DATABASE COMERCIO_DW
GO

USE COMERCIO_DW
GO

CREATE TABLE DIM_VENDEDOR (
    IDSK INT PRIMARY KEY IDENTITY,
    IDVENDEDOR INTEGER,
    INICIO DATETIME,
    FIM DATETIME,
    NOME VARCHAR(100),
    SEXO VARCHAR(20),
    IDGERENTE INTEGER
)
GO

CREATE TABLE DIM_NOTA (
    IDSK INTEGER PRIMARY KEY IDENTITY,
    IDNOTA INTEGER    
)
GO
--DROP TABLE DIM_NOTA

SELECT * FROM DIM_NOTA

CREATE TABLE DIM_FORMA (
    IDSK INTEGER PRIMARY KEY IDENTITY,
    IDFORMA INTEGER,
    FORMA VARCHAR(30)

)
GO

CREATE TABLE DIM_CLIENTE (
    IDSK INTEGER PRIMARY KEY IDENTITY,
    IDCLIENTE INTEGER,
    INICIO DATETIME,
    FIM DATETIME,
    NOME VARCHAR(100),
    SEXO VARCHAR(20),
    EMAIL VARCHAR(50),
    NASCIMENTO DATE,
    CIDADE VARCHAR(100),
    ESTADO VARCHAR(30)
)
GO

CREATE TABLE CATEGORIA(
	IDCATEGORIA INTEGER PRIMARY KEY,
	NOME VARCHAR(50)
)
GO

CREATE TABLE DIM_PRODUTO (
    IDSK INTEGER PRIMARY KEY IDENTITY,
    IDPRODUTO INTEGER,
    INICIO DATETIME,
    FIM DATETIME,
    NOME VARCHAR(100),
	VALOR_UNITARIO NUMERIC(10,2),
	CUSTO_MEDIO NUMERIC(10,2),
	ID_CATEGORIA INTEGER,
	CONSTRAINT FK_CATEGORIA FOREIGN KEY(ID_CATEGORIA) REFERENCES CATEGORIA(IDCATEGORIA)
)
GO
--DROP TABLE DIM_PRODUTO
SELECT * FROM DIM_PRODUTO


CREATE TABLE DIM_FORNECEDOR (
    IDSK INTEGER PRIMARY KEY IDENTITY,
    IDFORNECEDOR INTEGER,
    INICIO DATETIME,
    FIM DATETIME,
    NOME VARCHAR(50)
)
GO

CREATE TABLE DIM_TEMPO (
    IDSK INTEGER PRIMARY KEY IDENTITY,
    DATA DATE,
    DIA CHAR(2),
    DIASEMANA VARCHAR(10),
    MES CHAR(2),
    NOMEMES VARCHAR(20),
    QUARTO TINYINT,
    NOMEQUARTO VARCHAR(20),
    ANO CHAR(4),
    ESTACAOANO VARCHAR(20),
    FIMSEMANA CHAR(3),
    DATACOMPLETA VARCHAR(10)
)
GO

CREATE TABLE FATO (
    IDNOTA INTEGER REFERENCES DIM_NOTA(IDSK),
    IDCLIENTE INTEGER REFERENCES DIM_CLIENTE(IDSK),
    IDVENDEDOR INTEGER REFERENCES DIM_VENDEDOR(IDSK),
    IDFORMA INTEGER REFERENCES DIM_FORMA(IDSK),
    IDPRODUTO INTEGER REFERENCES DIM_PRODUTO(IDSK),
    IDFORNECEDOR INTEGER REFERENCES DIM_FORNECEDOR(IDSK),
    IDTEMPO INTEGER REFERENCES DIM_TEMPO(IDSK),
    QUANTIDADE INTEGER,
    TOTALITEM NUMERIC(10,2),
    CUSTOTOTAL NUMERIC(10,2),
    LUCROTOTAL NUMERIC(10,2)
)
GO
--DROP TABLE FATO
--GO
SELECT * FROM  FATO

--DROP TABLE DIM_PRODUTO
--GO