USE COMERCIO_OLTP
SELECT * FROM CLIENTE
--1000
INSERT INTO CLIENTE VALUES('MARIO','SOARES','MSOARES@IG.COM','M','1981-02-07')
SELECT * FROM CLIENTE
--1001

USE BI_ERROR
SELECT * FROM [ER_ ENDERECO]

USE COMERCIO_STAGE
--SELECT * FROM ST_CLIENTE
SELECT * FROM ST_VENDEDOR


SELECT * FROM
COMERCIO_STAGE.DBO.ST_PRODUTO

SELECT * FROM
PRODUTO


USE COMERCIO_STAGE
SELECT * FROM ST_FORMA

USE COMERCIO_OLTP
SELECT * FROM FORMA_PAGAMENTO

USE COMERCIO_STAGE
SELECT * FROM ST_FORNECEDOR

USE COMERCIO_OLTP
SELECT * FROM FORNECEDOR

USE COMERCIO_STAGE
SELECT * FROM ST_NOTA

USE COMERCIO_OLTP
SELECT * FROM NOTA_FISCAL


