USE COMERCIO_OLTP
SELECT * from CLIENTE
GO	
SELECT * FROM ENDERECO
GO
select * from categoria
GO
SELECT * FROM FORNECEDOR
GO
SELECT * FROM PRODUTO
GO
SELECT * FROM [dbo].[VENDEDOR]
GO
SELECT * FROM [dbo].[FORMA_PAGAMENTO]
GO
SELECT * FROM [dbo].[NOTA_FISCAL]
GO
SELECT* FROM [dbo].[ITEM_NOTA]
GO
--AUTORRELACIONAMENTO VENDEDOR X GERENTE
SELECT G.IDVENDEDOR AS ID_GERENTE, G.NOME AS GERENTE, V.IDVENDEDOR, V.NOME AS VENDEDOR 
FROM VENDEDOR G
	INNER JOIN VENDEDOR V
	ON V.IDVENDEDOR = G.ID_GERENTE
GO
/*RELAÇÃO ENTRE TABELAS*/
SELECT C.NOME, C.SOBRENOME,C.SEXO,N.DATA,N.IDNOTA,P.PRODUTO,N.TOTAL
FROM CLIENTE C
INNER JOIN NOTA_FISCAL N
ON C.IDCLIENTE = N.ID_CLIENTE
INNER JOIN ITEM_NOTA I
ON N.IDNOTA = I.ID_NOTA_FISCAL
INNER JOIN PRODUTO P
ON P.IDPRODUTO = I.ID_PRODUTO
ORDER BY 5
GO





